### ISSUE TITLE
TS file sample with japanese caption

### ISSUE THREAD

**Issue by andrelcm** [nkoriyama/aribb24#15]
Does anyone have a ts file sample with an arib b24 stream?
I'd like to perform some tests before trying to implement portuguese support, but I can't find a working file.

**Comment by fcartegnie** [comment]
https://streams.videolan.org/streams/ts/ARIB/

But if you need other samples, you probably don't have the right plan. 
You'll only need new to provide symbol tables and a way to switch standard.

**Comment by andrelcm** [comment]
Thank you.
